import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import walletRouter from "./wallet.js";
import ridesRouter from "./rides.js";
import locationsRouter from "./locations.js";
import categoriesRouter from "./categories.js";
import pharmacyRouter from "./pharmacy.js";
import parcelRouter from "./parcel.js";
import notificationsRouter from "./notifications.js";
import addressesRouter from "./addresses.js";
import settingsRouter from "./settings.js";
import seedRouter from "./seed.js";
import adminRouter from "./admin.js";
import platformConfigRouter from "./platform-config.js";
import riderRouter from "./rider.js";
import vendorRouter from "./vendor.js";
import paymentsRouter from "./payments.js";
import reviewsRouter from "./reviews.js";
import systemRouter from "./system.js";
import mapsRouter, { adminMapsRouter } from "./maps.js";
import schoolRouter from "./school.js";
import uploadsRouter from "./uploads.js";
import sosRouter from "./sos.js";
import recommendationsRouter from "./recommendations.js";
import bannersRouter from "./banners.js";
import variantsRouter from "./variants.js";
import pushRouter from "./push.js";
import kycRouter from "./kyc.js";
import wishlistRouter from "./wishlist.js";
import vanRouter from "./van.js";
import webhooksRouter from "./webhooks.js";
import deliveryEligibilityRouter from "./delivery-eligibility.js";
import appConfigRouter from "./app-config.js";
import areaLocationsRouter from "./area-locations.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/products", productsRouter);
router.use("/orders", ordersRouter);
router.use("/wallet", walletRouter);
router.use("/rides", ridesRouter);
router.use("/locations", locationsRouter);
router.use("/categories", categoriesRouter);
router.use("/pharmacy-orders", pharmacyRouter);
router.use("/parcel-bookings", parcelRouter);
router.use("/notifications", notificationsRouter);
router.use("/addresses", addressesRouter);
router.use("/settings/app-config", appConfigRouter);
router.use("/settings", settingsRouter);
router.use("/seed", seedRouter);
router.use("/admin/system", systemRouter);
router.use("/admin", adminRouter);
router.use("/platform-config", platformConfigRouter);
router.use("/rider", riderRouter);
router.use("/vendor", vendorRouter);
router.use("/payments", paymentsRouter);
router.use("/reviews", reviewsRouter);
router.use("/maps", mapsRouter);
/* /api/admin/maps/{test|usage|cache/clear} — dedicated admin maps router
   so admin clients using the /api/admin prefix reach the right handlers.
   These endpoints match the task's required contract exactly. */
router.use("/admin/maps", adminMapsRouter);
router.use("/school", schoolRouter);
router.use("/uploads", uploadsRouter);
router.use("/sos", sosRouter);
router.use("/recommendations", recommendationsRouter);
router.use("/banners", bannersRouter);
router.use("/variants", variantsRouter);
router.use("/push", pushRouter);
router.use("/kyc", kycRouter);
router.use("/wishlist", wishlistRouter);
router.use("/van", vanRouter);
router.use("/webhooks", webhooksRouter);
router.use("/delivery/eligibility", deliveryEligibilityRouter);
router.use("/area-locations", areaLocationsRouter);

export default router;
